#!/bin/sh
now=$(date +%F_%T)
echo "$now - weekly lists updated" >> /tmp/deezerupdates

generate_post_data()
{
  cat <<EOF
{
  "quality": "DEEZQUALITY",
  "url": [
  DEEZPLAYLIST
  ]
}
EOF
}

curl -X POST -H "Content-Type: application/json" \
 -d "$(generate_post_data)" \
 http://DEEZSERVER/api/download/
